# Generated by Django 4.1.1 on 2022-09-26 22:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0002_articulo_cuerpo_articulo_imagen_articulo_sub_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
