# Generated by Django 4.1.1 on 2022-10-03 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userapp', '0002_rename_user_avatar_user_alter_avatar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=600, null=True)),
                ('link_web', models.URLField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
